### ISSUE TITLE
Handle disconnected devices properly

### ISSUE THREAD

**Issue by PPCM** [mozilla-iot/thing-url-adapter#81] opened 2019-11-26 08:43 UTC
After the issue #80 I notice an other issue now.
The device is registred with its URL and it responds correctly.

When I plug off the device, it is still actice on the gateway. I can change its state, but if I reload the page, the state of the device stay on the state when it was unplugged.
Not ideal ...

**Comment by mrstegeman** [comment] 2019-12-26 17:33
The problem is that a serviceDown mDNS message is not being sent by the ESP. I believe if you wait a little while (maybe up to a minute), one will occur automatically, and the device should be marked as offline (i.e. dimmed in the UI). Is that true?

**Comment by PPCM** [comment] 2020-01-12 20:50
It's true, but I have to wait more than 10mn
Thanks for the answer...

**Comment by mrstegeman** [comment] 2020-01-13 17:41
#90 should reduce the maximum timeout to roughly 30 seconds.

**Comment by PPCM** [comment] 2020-01-13 21:02
Thanks

**Closed** 2020-01-17 21:32 UTC
